//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubject
    {
        public int Id { get; set; }
        public string sName { get; set; }
        public Nullable<int> cId { get; set; }
    
        public virtual tblCourse tblCourse { get; set; }
    }
}
