//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackTrackingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAssessment()
        {
            this.tblFeedbacks = new HashSet<tblFeedback>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> AssessmentTypeId { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
    
        public virtual tblCourse tblCourse { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblGrade tblGrade { get; set; }
        public virtual tblAssessmentType tblAssessmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFeedback> tblFeedbacks { get; set; }
    }
}
