//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackTrackingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNote
    {
        public int Id { get; set; }
        public string Notes { get; set; }
        public Nullable<int> FeedbackId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tblFeedback tblFeedback { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
